- src/components/Footer.jsx
added github icon link to footer
closes #7
> added github icon link to footer

- src/components/Footer.jsx
> Simplified footer

- src/components/AutoComplete.jsx
- src/layouts/ControlContainer.jsx
- src/layouts/Main.jsx
- src/layouts/ScheduleContainer.jsx
> Bug fix #15

- src/components/MarathonPref.jsx
- src/layouts/ControlContainer.jsx
Simplified the component, functionality is the same.
> Refactored MarathonPref

- src/components/AutoComplete.jsx
closes https://github.com/Exanut/schedubuddy-web/issues/18
> autcomplete bugfix

- src/components/Schedule.jsx
- src/layouts/ScheduleContainer.jsx
closes https://github.com/Exanut/schedubuddy-web/issues/21
> Draw instructor name when component is unique

- src/components/TimePick.jsx
- src/layouts/ControlContainer.jsx
Time picker control state is now inline with it's query parameter representation.
Removed the previous time picker state conversion logic in submit handler and other redundant toString() lines.
> Time picker refactor

- src/components/AutoComplete.jsx
- src/layouts/ControlContainer.jsx
Chip/Schedule colors are now determined by alphabetical order
closes #25
> Bug fix #25

- jsconfig.json
- src/App.js
- src/index.js
Made a jsconfig.json file at the app root level that should allow for cleaner imports (root directory is now app).
Converted a few imports to verify that the website builds properly before converting all.
> Absolute Imports (Test Push)

- src/layouts/ControlContainer.jsx
ControlContainer no longer uses grid for positioning, layout complexity reduced a bit.
> Removed grid positioning from ControlContainer

- src/components/ChipAutoComplete.jsx
- src/layouts/ControlContainer.jsx
- Got rid of the static view class
- Renamed AutoCompleteInput to ChipAutoComplete
> Simplified view changing

- src/layouts/ControlContainer.jsx
- Added tooltip
- Changed button container
- Made button color="primary" when it's corresponding view is active
> Altered view button styling

- src/components/FormSwitcher.jsx
- src/layouts/Main.jsx
https://github.com/Exanut/schedubuddy-web/issues/40
Does this seem fine?
> move form switcher above control

- public/index.html
- src/components/FormSwitcher.jsx
- src/layouts/Main.jsx
New colors, new font, new imported component
> Refactor+Restyle Tabs

- src/components/Schedule.jsx
Temp fix, changes to API response need to be made to avoid parsing entirely.
@Exanut
> Quick fix for parsing error

- src/components/Schedule.jsx
- src/layouts/Main.jsx
Sorted and removed duplicates from courseOrder before assigning colors to courses
> Fix color coding in room schedule

- src/components/Footer.jsx
Removed footer text and Instagram link
> Removed footer text and Instagram link

- src/components/ChipAutoComplete.jsx
- src/components/Paging.jsx
- src/forms/Room.jsx
- src/forms/Schedule.jsx
- src/layouts/UnderConstruction.jsx
This removes the majority of inline styles
> Change inline styles to sx

- src/components/ChipAutoComplete.jsx
- src/components/FormSwitcher.jsx
- src/forms/FreeRoom.jsx
- src/forms/Room.jsx
- src/forms/Schedule.jsx
- src/layouts/FreeRoomContainer.jsx
- src/layouts/Main.jsx
Basic implementation of the new free rooms feature
Some things I'd like to add later:
- Full building names
- Pagination to the display list, it can get a bit long
> Free Rooms Feature

- src/components/Footer.jsx
> Added donate iconButton

- src/components/CourseLock.jsx
- src/forms/Schedule.jsx
- src/layouts/Main.jsx
https://github.com/aarctan/schedubuddy-web/issues/64
> Prototype support for whitelisting/blacklisting classes

- package-lock.json
- src/layouts/Main.jsx
Previously the URL would be generated with spaces etc. causing isssues when sharing to discord. I added proper encoding to fix this
> Fixing URL Generated

- src/components/ShareButton.jsx
- src/forms/Schedule.jsx
- src/layouts/Main.jsx
- src/layouts/ScheduleContainer.jsx
Previously, share schedule would share all current filters applied. I have updated it to only share the current page being viewed
> Fixing Sharing Schedule behaviour

- src/components/CourseLock.jsx
> fixed: course filtering bug

- src/components/ShareButton.jsx
> Use copy icon for share

- src/components/Schedule.jsx
- Fix `let` variables that should be assigned as `const`
- Simplify startToInt function
- Simplify some of the computations in drawSchedule and drawText
- Create helper function to setup the canvas
- Fix `Multiple readback operations using getImageData` warning
- Use `useRef` hook instead of `createRef`
- Extend `convertCanvasToImage` function
@mdziubin @aarctan
> Clean up of schedule component

- src/components/Paging.jsx
- src/components/ShareButton.jsx
- src/layouts/ScheduleContainer.jsx
Share button is less intense
Pagination was too stuck to the schedule added margin
> Update share icon
